### ISSUE TITLE
[TC-CNET-4.9] Test case get fails in UI

### ISSUE THREAD

**Issue by KishokG** [project-chip/certification-tool#118]
### Describe the bug

TC-CNET-4.9 test case is failing in step 2, 4, 7, 8, 10, 12, 14.

### Steps to reproduce the behavior

1. From the Test-Harness user interface loaded the Network Commissioning Test Plan(WiFi).xml PICS file to select the test cases.
2. Selected the TC-CNET-4.9 Semi-Automated test case to executed.
3. Executed the below mentioned command to put DUT into a commissionable state, ./chip-all-clusters-app --wifi
4. Click the Start button on Test-Harness user interface.

### Expected behavior

TC should execute successfully without error.

### Log files

[CNET-4_9_2023_12_13_16_58_50.log](https://github.com/project-chip/certification-tool/files/13660260/CNET-4_9_2023_12_13_16_58_50.log)

**Report:** 
 [TC-CNET-4.9.pdf](https://github.com/project-chip/certification-tool/files/13660284/TC-CNET-4.9.pdf)

### PICS file

[Network Commissioning Test Plan(WiFi).zip](https://github.com/project-chip/certification-tool/files/13660276/Network.Commissioning.Test.Plan.WiFi.zip)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/133193761/ea695965-db50-4b47-ad45-0b7ae59b033f)

### Environment

Version: main - dev
Sha: f17efc4

**Comment by antonio-amjr** [comment]
Hi @KishokG,

Analyzing the erros in the logs I noticed some results entries with `'NetworkID': b'GRLPrivate'` while the expected value is `'NetworkID': b'zigbeehome'`.
That happens because the default value for the SSID name is indeed "zigbeehome" as you can see below:
```
# TC-CNET-4.9 YAML file
config:
    nodeId: 0x12344321
    cluster: "Network Commissioning"
    endpoint: 0
    PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID:
        type: octet_string
        defaultValue: "hex:7A6967626565686F6D65" # zigbeehome in hex string
```

Can you try something for me?
Try editing the project's config file, changing "test_parameters" to the following:
```
"test_parameters": {
      "PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID": "hex:47524C50726976617465"
    }
```
The value "hex:47524C50726976617465" is equivalent to the string `GRLPrivate`.

Let me know the results.
