### ISSUE TITLE
[TSTAT-2-1] [TSTAT-2-2] Setback is not selected in PICS but TH continues to test it

### ISSUE THREAD

**Issue by raju-apple** [project-chip/certification-tool#29]
From chip-certification-tool created by [pankore](https://github.com/pankore): CHIP-Specifications/chip-certification-tool#870  

## Description:
In PICS and zap, we unchecked the Setback related attributes, but TH continues to test for it, causing failure

## Logs:
[TC-TSTAT-2-1_2023_06_15_16_39_48.log](https://github.com/CHIP-Specifications/chip-certification-tool/files/11755128/TC-TSTAT-2-1_2023_06_15_16_39_48.log)

## Additional Info:
v2.8.1 test harness
PICS tool v1.6.6

**Comment by raju-apple** [comment]
Looking at the the _**Test_TC_TSTAT_2_1.yaml**_ we have:

```
-label: "Read OccupiedSetback attribute from the DUT"
      PICS: TSTAT.S.F02
      command: "readAttribute"
      attribute: "OccupiedSetback"
      response:
          constraints:
              type: int8u
              minValue: 0
              maxValue: 255

    - label: "Read OccupiedSetbackMin attribute from the DUT"
      PICS: TSTAT.S.F02
      command: "readAttribute"
      attribute: "OccupiedSetbackMin"
      response:
          constraints:
              type: int8u
              minValue: 0
              maxValue: 255

    - label: "Read OccupiedSetbackMax attribute from the DUT"
      PICS: TSTAT.S.F02
      command: "readAttribute"
      attribute: "OccupiedSetbackMax"
      response:
          constraints:
              type: int8u
              minValue: 0
              maxValue: 255
```

PICS values (from log):
```
...
TSTAT.S.F02=1
...
```
According your log we can see the PICS value _**TSTAT.S.F02=1**_ .  So these tests steps aren't skipped.
Test steps (from log):
```
...
CHIPTOOL   | 2023-06-15 08:40:37.919422 | [1686818433.350033][25:33] CHIP:TOO:  ***** Test Step 53 : Read OccupiedSetback attribute from the DUT
...
CHIPTOOL   | 2023-06-15 08:40:39.888556 | [1686818434.031344][25:33] CHIP:TOO:  ***** Test Step 55 : Read OccupiedSetbackMax attribute from the DUT
...
CHIPTOOL   | 2023-06-15 08:40:38.950267 | [1686818433.690637][25:33] CHIP:TOO:  ***** Test Step 54 : Read OccupiedSetbackMin attribute from the DUT
...
```
